### ISSUE TITLE
Update cloudposse module version 

### ISSUE THREAD

**Issue by mayank0202** [sourcefuse/terraform-aws-arc-billing#11]
After upgrading the version. Please test the example folder

**Comment by mayank0202** [comment]
I am hoping there TF registry gets updated , Already raised an issue 
https://github.com/cloudposse/terraform-aws-budgets/issues/40
If its not resolved then we can fetch the latest tag from github rather than from TF registry

**Comment by divyaperumal-sf** [comment]
The pull request has been approved and merged into the main branch. Hence, closing the ticket.
